package ExtendedRoute.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import java.util.Map;
import java.util.HashMap;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      Integer preIndex = indices_xbvbvu_a0a.get(cncpt);
      int switchIndex = (preIndex == null ? -1 : preIndex);
      switch (switchIndex) {
        case 0:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new GoStraight2_Editor());
          }
          break;
        case 1:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new GoStraight3_Editor());
          }
          break;
        case 2:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new NewBoundary_Editor());
          }
          break;
        case 3:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new Variable_Editor());
          }
          break;
        case 4:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new VariableReference_Editor());
          }
          break;
        default:
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static Map<SAbstractConcept, Integer> buildConceptIndices(SAbstractConcept... concepts) {
    HashMap<SAbstractConcept, Integer> res = new HashMap<SAbstractConcept, Integer>();
    int counter = 0;
    for (SAbstractConcept c : concepts) {
      res.put(c, counter++);
    }
    return res;
  }
  private static final Map<SAbstractConcept, Integer> indices_xbvbvu_a0a = buildConceptIndices(MetaAdapterFactory.getConcept(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0ddf66ccL, "ExtendedRoute.structure.GoStraight2"), MetaAdapterFactory.getConcept(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x51428e98e99db172L, "ExtendedRoute.structure.GoStraight3"), MetaAdapterFactory.getConcept(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0ddf4fc9L, "ExtendedRoute.structure.NewBoundary"), MetaAdapterFactory.getConcept(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0dde5167L, "ExtendedRoute.structure.Variable"), MetaAdapterFactory.getConcept(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x50d35724d69a0deeL, "ExtendedRoute.structure.VariableReference"));
}
