package ExtendedRoute.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(5);
  /*package*/ final ConceptDescriptor myConceptGoStraight2 = createDescriptorForGoStraight2();
  /*package*/ final ConceptDescriptor myConceptGoStraight3 = createDescriptorForGoStraight3();
  /*package*/ final ConceptDescriptor myConceptNewBoundary = createDescriptorForNewBoundary();
  /*package*/ final ConceptDescriptor myConceptVariable = createDescriptorForVariable();
  /*package*/ final ConceptDescriptor myConceptVariableReference = createDescriptorForVariableReference();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptGoStraight2.getId(), 0);
    myIndexMap.put(myConceptGoStraight3.getId(), 1);
    myIndexMap.put(myConceptNewBoundary.getId(), 2);
    myIndexMap.put(myConceptVariable.getId(), 3);
    myIndexMap.put(myConceptVariableReference.getId(), 4);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptGoStraight2, myConceptGoStraight3, myConceptNewBoundary, myConceptVariable, myConceptVariableReference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptGoStraight2;
      case 1:
        return myConceptGoStraight3;
      case 2:
        return myConceptNewBoundary;
      case 3:
        return myConceptVariable;
      case 4:
        return myConceptVariableReference;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForGoStraight2() {
    return new ConceptDescriptorBuilder("ExtendedRoute.structure.GoStraight2", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0ddf66ccL)).super_("RouteLang.structure.Operation").version(1).super_(MetaIdFactory.conceptId(0x3926ee37b1364f6cL, 0xaa6b199db0e76759L, 0x11412d0ef0a0f3e1L)).parents("RouteLang.structure.Operation").parentIds(MetaIdFactory.conceptId(0x3926ee37b1364f6cL, 0xaa6b199db0e76759L, 0x11412d0ef0a0f3e1L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x17f1e1fb0ddf6703L, "va", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0dde5167L), false, new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "1725408600645396227"))).references("va").alias("GoStraight", "").sourceNode(new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "1725408600645396172")).create();
  }
  private static ConceptDescriptor createDescriptorForGoStraight3() {
    return new ConceptDescriptorBuilder("ExtendedRoute.structure.GoStraight3", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x51428e98e99db172L)).super_("RouteLang.structure.Operation").version(1).super_(MetaIdFactory.conceptId(0x3926ee37b1364f6cL, 0xaa6b199db0e76759L, 0x11412d0ef0a0f3e1L)).parents("RouteLang.structure.Operation").parentIds(MetaIdFactory.conceptId(0x3926ee37b1364f6cL, 0xaa6b199db0e76759L, 0x11412d0ef0a0f3e1L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x50d35724d697fbe6L, "child", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), false, false, false, new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "5824094558850907110"))).children(new String[]{"child"}, new boolean[]{false}).alias("GoStraight3", "xxx").sourceNode(new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "5855399252940665202")).create();
  }
  private static ConceptDescriptor createDescriptorForNewBoundary() {
    return new ConceptDescriptorBuilder("ExtendedRoute.structure.NewBoundary", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0ddf4fc9L)).super_("RouteLang.structure.Boundary").version(1).super_(MetaIdFactory.conceptId(0x3926ee37b1364f6cL, 0xaa6b199db0e76759L, 0x204df38215086eeaL)).parents("RouteLang.structure.Boundary", "jetbrains.mps.execution.util.structure.IMainClass").parentIds(MetaIdFactory.conceptId(0x3926ee37b1364f6cL, 0xaa6b199db0e76759L, 0x204df38215086eeaL), MetaIdFactory.conceptId(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x17f1e1fb0ddf4fe5L, "varibles", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0dde5167L), true, true, false, new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "1725408600645390309"))).children(new String[]{"varibles"}, new boolean[]{true}).rootable().sourceNode(new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "1725408600645390281")).create();
  }
  private static ConceptDescriptor createDescriptorForVariable() {
    return new ConceptDescriptorBuilder("ExtendedRoute.structure.Variable", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0dde5167L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x17f1e1fb0ddf4e0fL, "value", new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "1725408600645389839"))).properties("value").sourceNode(new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "1725408600645325159")).create();
  }
  private static ConceptDescriptor createDescriptorForVariableReference() {
    return new ConceptDescriptorBuilder("ExtendedRoute.structure.VariableReference", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x50d35724d69a0deeL)).super_("jetbrains.mps.baseLanguage.structure.Expression").version(1).super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x50d35724d69aff6fL, "variable", MetaIdFactory.conceptId(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0dde5167L), false, new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "5824094558851104623"))).references("variable").sourceNode(new SNodePointer("r:cd9de5e8-c485-486d-8532-7d6e48ae5a86(ExtendedRoute.structure)", "5824094558851042798")).create();
  }
}
