package ExtendedRoute.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_5824094558851183549(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x50d35724d69a0deeL, 0x50d35724d69aff6fL, "variable")), MetaAdapterFactory.getProperty(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0dde5167L, 0x17f1e1fb0ddf4e0fL, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_6760333528915844750(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0dde5167L, 0x17f1e1fb0ddf4e0fL, "value"));
  }
  public static SNode sourceNodeQuery_6760333528915815060(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x17f1e1fb0ddf66ccL, 0x17f1e1fb0ddf6703L, "va"));
  }
  public static SNode sourceNodeQuery_4288912749912044054(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xcd8cd0fc0f424bbaL, 0x9454613f52f5f8a7L, 0x51428e98e99db172L, 0x50d35724d697fbe6L, "child"));
  }
}
